Task 22 - Created AdoDotNet Project
Software-Engineering-LNU/Software-Engineering-Project pull request #26
Opened 2022-10-13 15:28 UTC by SergiyVengrin

Closes #22

2022-10-15 18:58 UTC, OleksiiDatsiuk requested changes

2022-10-15 18:58 UTC, OleksiiDatsiuk commented on EmployeestSeedConsoleApp/Program.cs
> +
You should better move db credentials into separate configuration/utils file

2022-10-15 19:05 UTC, OleksiiDatsiuk commented on EmployeestSeedConsoleApp/Program.cs
> +string connectionString = $"Host=localhost;Port=5432;Database=CommentsDb;Username={dbUsername};Password={dbPassword}";
Also, this link doesn't satisfy our requirements. We will use an external database, which means that the host, port, and db name must also be injected as environment variables

2022-10-15 19:13 UTC, OleksiiDatsiuk commented on EmployeestSeedConsoleApp/Program.cs
> +    Console.WriteLine($"Database: {sqlConnection.Database}");
Not sure if we even need this writelines, you should better remove them

2022-10-16 17:18 UTC, DarkPhoeniix requested changes

2022-10-16 17:18 UTC, DarkPhoeniix commented on EmployeestSeedConsoleApp.sln
> +EndGlobal
We already have another solution file in the project directory. I think you should remove the unused one.

2022-10-16 17:18 UTC, DarkPhoeniix commented on EmployeestSeedConsoleApp/Program.cs
> +
Also, prefer to avoid shortenings in the names of variables.

2022-10-16 17:18 UTC, DarkPhoeniix commented on EmployeestSeedConsoleApp/Program.cs
> +﻿using Npgsql;
Is this line necessary?

2022-10-16 20:58 UTC, SergiyVengrin commented on EmployeestSeedConsoleApp/Program.cs
> +    Console.WriteLine($"Database: {sqlConnection.Database}");
I thought it's a good way to prove that connection is successful

2022-10-17 04:58 UTC, DarkPhoeniix commented on EmployeestSeedConsoleApp/Program.cs
> +    Console.WriteLine($"Database: {sqlConnection.Database}");
I think it would be better to move such messages to the logs

2022-10-17 17:01 UTC, OleksiiDatsiuk approved these changes

2022-10-18 10:08 UTC, closed without merging